-- NPC name fixes: Wowhead -> DB corrections
-- Generated by compare_npc_names.py
-- Total fixes: 379

UPDATE `creature_template` SET `name` = 'Dark Iron Pillamaster' WHERE `entry` = 14636; -- was: Chambermaid Pillaclencher
UPDATE `creature_template` SET `name` = 'Craig\'s Test Human' WHERE `entry` = 25537; -- was: Craig's Test Human A
UPDATE `creature_template` SET `name` = 'Recalled Silverbrook Villager' WHERE `entry` = 26708; -- was: Silverbrook Villager
UPDATE `creature_template` SET `name` = 'Vic\'s Flying Machine' WHERE `entry` = 28710; -- was: Flying Mount
UPDATE `creature_template` SET `name` = 'Stormwind Harbor Guard' WHERE `entry` = 29712; -- was: StormwindHarbor Guard
UPDATE `creature_template` SET `name` = 'Totally Generic Bunny (All Phase)' WHERE `entry` = 32520; -- was: TotallyGenericBunny(All Phase)
UPDATE `creature_template` SET `name` = 'Riding Proto-Drake, Blue' WHERE `entry` = 32585; -- was: Riding Protodrake, Blue
UPDATE `creature_template` SET `name` = 'Riding Proto-Drake, Bronze' WHERE `entry` = 32586; -- was: Riding Protodrake, Bronze
UPDATE `creature_template` SET `name` = 'Explorers\' League Digger' WHERE `entry` = 38998; -- was: Explorer's League Digger
UPDATE `creature_template` SET `name` = 'Mutated Hatchling' WHERE `entry` = 39388; -- was: Twilight Hatchling
UPDATE `creature_template` SET `name` = 'Molten Giant' WHERE `entry` = 40166; -- was: Enslaved Gronn Brute
UPDATE `creature_template` SET `name` = 'Invoked Shadowflame Spirit' WHERE `entry` = 40357; -- was: Invoked Flaming Spirit
UPDATE `creature_template` SET `name` = 'Twilight Destroyer' WHERE `entry` = 41095; -- was: Twilight Drake
UPDATE `creature_template` SET `name` = 'Draenei Earth Totem' WHERE `entry` = 45348; -- was: DraeneiEarth Totem
UPDATE `creature_template` SET `name` = 'Draenei Water Totem' WHERE `entry` = 45352; -- was: DraeneiWater Totem
UPDATE `creature_template` SET `name` = 'Draenei Air Totem' WHERE `entry` = 45354; -- was: DraeneiAir Totem
UPDATE `creature_template` SET `name` = 'Explorers\' League Digger' WHERE `entry` = 46232; -- was: Explorer's League Digger
UPDATE `creature_template` SET `name` = 'Waters of Farseeing Kill Credit' WHERE `entry` = 50054; -- was: Waters of Farseeing
UPDATE `creature_template` SET `name` = 'Stormwind Gryphon Rider' WHERE `entry` = 51348; -- was: StormwindGryphon Rider
UPDATE `creature_template` SET `name` = 'Explorers\' League Scout' WHERE `entry` = 51545; -- was: Explorer's League Scout
UPDATE `creature_template` SET `name` = 'Ice Lance' WHERE `entry` = 54060; -- was: Voracious Hatchling (1)
UPDATE `creature_template` SET `name` = 'Explorers\' League Surveyor' WHERE `entry` = 68328; -- was: Explorer's League Surveyor
UPDATE `creature_template` SET `name` = 'Explorers\' League Researcher' WHERE `entry` = 68971; -- was: Explorer's League Researcher
UPDATE `creature_template` SET `name` = 'Grotan the Herald' WHERE `entry` = 71716; -- was: Herold Grotan
UPDATE `creature_template` SET `name` = 'Lowborn Servant' WHERE `entry` = 75976; -- was: Outcast Servant
UPDATE `creature_template` SET `name` = 'Suntalon Tamer' WHERE `entry` = 76154; -- was: Sun Talon Tamer
UPDATE `creature_template` SET `name` = 'Outcast Warrior' WHERE `entry` = 76205; -- was: Blooded Bladefeather
UPDATE `creature_template` SET `name` = 'Shadowmoon Dominator' WHERE `entry` = 76446; -- was: Shadowmoon Enslaver
UPDATE `creature_template` SET `name` = 'Suntalon' WHERE `entry` = 79093; -- was: Skyreach Sun Talon
UPDATE `creature_template` SET `name` = 'Poker' WHERE `entry` = 86487; -- was: Poker the Monster
UPDATE `creature_template` SET `name` = 'Arator the Redeemer' WHERE `entry` = 97071; -- was: Arator
UPDATE `creature_template` SET `name` = 'Arator the Redeemer' WHERE `entry` = 97086; -- was: Arator
UPDATE `creature_template` SET `name` = 'Sashj\'tar Reef Runner' WHERE `entry` = 99070; -- was: Sashj'tar Diviner
UPDATE `creature_template` SET `name` = 'Totem of Wrath' WHERE `entry` = 105427; -- was: Skyfury Totem
UPDATE `creature_template` SET `name` = 'Armor Polish Kill Credit' WHERE `entry` = 108787; -- was: Baby Dog
UPDATE `creature_template` SET `name` = '"The Imposter" Quest SI:7 Courtyard Reached Kill Credit & POI Marker' WHERE `entry` = 111190; -- was: TheImposter QuestSI:7CourtyardReachedKillCredit&POI Marker
UPDATE `creature_template` SET `name` = 'Felguard Legionnaire' WHERE `entry` = 118708; -- was: Felguard Legionaire
UPDATE `creature_template` SET `name` = 'Saftey Vehicle to Center Platform - From W/N Platform' WHERE `entry` = 121475; -- was: Wind
UPDATE `creature_template` SET `name` = 'Saftey Vehicle to Center Platform - From W/S Platform' WHERE `entry` = 121476; -- was: Wind
UPDATE `creature_template` SET `name` = 'Saftey Vehicle to Center Platform - From NE Platform' WHERE `entry` = 121477; -- was: Wind
UPDATE `creature_template` SET `name` = 'Saftey Vehicle to Center Platform - From NW Platform' WHERE `entry` = 121478; -- was: Wind
UPDATE `creature_template` SET `name` = 'Saftey Vehicle to Center Platform - From SE Platform' WHERE `entry` = 121479; -- was: Wind
UPDATE `creature_template` SET `name` = 'Arator the Redeemer' WHERE `entry` = 121890; -- was: Arator
UPDATE `creature_template` SET `name` = 'Sapped Voidlord' WHERE `entry` = 122398; -- was: Weakened Voidcaller
UPDATE `creature_template` SET `name` = 'Signal Crystal' WHERE `entry` = 123344; -- was: Navigation Console
UPDATE `creature_template` SET `name` = 'Rejuvenated Voidlord' WHERE `entry` = 123411; -- was: Abyssal Devourer
UPDATE `creature_template` SET `name` = 'Explorers\' League Prospector' WHERE `entry` = 123798; -- was: Explorer's League Prospector
UPDATE `creature_template` SET `name` = 'Explorers\' League Scout' WHERE `entry` = 123805; -- was: Explorer's League Scout
UPDATE `creature_template` SET `name` = 'Explorers\' League Surveyor' WHERE `entry` = 123808; -- was: Explorer's League Surveyor
UPDATE `creature_template` SET `name` = 'Explorers\' League Scout' WHERE `entry` = 124213; -- was: Explorer's League Scout
UPDATE `creature_template` SET `name` = 'Explorers\' League Prospector' WHERE `entry` = 124214; -- was: Explorer's League Prospector
UPDATE `creature_template` SET `name` = 'Void Trap' WHERE `entry` = 124427; -- was: Void Bomb
UPDATE `creature_template` SET `name` = 'Explorers\' League Surveyor' WHERE `entry` = 126985; -- was: Explorer's League Surveyor
UPDATE `creature_template` SET `name` = 'Explorers\' League Scout' WHERE `entry` = 128049; -- was: Explorer's League Scout
UPDATE `creature_template` SET `name` = 'Explorers\' League Surveyor' WHERE `entry` = 128050; -- was: Explorer's League Surveyor
UPDATE `creature_template` SET `name` = 'Speak to Jo\'chunga in pool proxy credit' WHERE `entry` = 129333; -- was: Jo'chunga
UPDATE `creature_template` SET `name` = 'Explorers\' League Summoner' WHERE `entry` = 129541; -- was: Explorer's League Summoner
UPDATE `creature_template` SET `name` = 'Silvermoon Sorceress' WHERE `entry` = 133200; -- was: Lady Jaina Proudmoore
UPDATE `creature_template` SET `name` = 'Irontide Curseblade' WHERE `entry` = 135258; -- was: Irontide Marauder
UPDATE `creature_template` SET `name` = 'Explorers\' League Prospector' WHERE `entry` = 135875; -- was: Explorer's League Prospector
UPDATE `creature_template` SET `name` = 'Explorers\' League Surveyor' WHERE `entry` = 135876; -- was: Explorer's League Surveyor
UPDATE `creature_template` SET `name` = '(Bunny) Pillaging Canoe' WHERE `entry` = 136320; -- was: Pillaging Canoe
UPDATE `creature_template` SET `name` = 'Explorers\' League Surveyor' WHERE `entry` = 136645; -- was: Explorer's League Surveyor
UPDATE `creature_template` SET `name` = 'Irontide Curseblade' WHERE `entry` = 138247; -- was: Irontide Marauder
UPDATE `creature_template` SET `name` = 'Kill Credit: Corruption' WHERE `entry` = 143127; -- was: Corruption
UPDATE `creature_template` SET `name` = 'Gork the Basher' WHERE `entry` = 156676; -- was: Ogre Overseer
UPDATE `creature_template` SET `name` = 'Kill Credit: Break Collector 1' WHERE `entry` = 157071; -- was: Break Collector 1
UPDATE `creature_template` SET `name` = 'Kill Credit: Break Collector 2' WHERE `entry` = 157072; -- was: Break Collector 2
UPDATE `creature_template` SET `name` = 'Kill Credit: Break Collector 3' WHERE `entry` = 157073; -- was: Break Collector 3
UPDATE `creature_template` SET `name` = 'Vulnerable Aspirant' WHERE `entry` = 157242; -- was: Vulnearable Aspirant
UPDATE `creature_template` SET `name` = 'Bathe in the Pool' WHERE `entry` = 158330; -- was: Bathbomb
UPDATE `creature_template` SET `name` = 'Animated Weapon' WHERE `entry` = 158649; -- was: Vorpalia
UPDATE `creature_template` SET `name` = 'Ring Bell' WHERE `entry` = 159590; -- was: Unstable Anomaly
UPDATE `creature_template` SET `name` = 'Disciple Fotima' WHERE `entry` = 159840; -- was: Desciple Fortina
UPDATE `creature_template` SET `name` = 'Prowling Soul-Eater' WHERE `entry` = 160780; -- was: Dusky Tremorbeast
UPDATE `creature_template` SET `name` = 'Captain Garrick' WHERE `entry` = 161350; -- was: Kalecgos
UPDATE `creature_template` SET `name` = 'Explorers\' League Researcher' WHERE `entry` = 161938; -- was: Explorer's League Researcher
UPDATE `creature_template` SET `name` = 'Kill Credit: Bearers Ordered' WHERE `entry` = 162877; -- was: Bearers Ordered
UPDATE `creature_template` SET `name` = 'Kill Credit: Centurions Ordered' WHERE `entry` = 162879; -- was: Centurions Ordered
UPDATE `creature_template` SET `name` = 'Alliance Sparring Partner' WHERE `entry` = 164577; -- was: Captain Garrick
UPDATE `creature_template` SET `name` = 'Generic Hunter Pet' WHERE `entry` = 165189; -- was: GenericHunter Pet
UPDATE `creature_template` SET `name` = 'The Jailer' WHERE `entry` = 165539; -- was: The Jailor
UPDATE `creature_template` SET `name` = 'Anima Canister' WHERE `entry` = 166223; -- was: Anima Can
UPDATE `creature_template` SET `name` = 'Kill Credit: Soulbind with Mikanikos' WHERE `entry` = 166737; -- was: Soulbind
UPDATE `creature_template` SET `name` = 'Carry Raw Materials' WHERE `entry` = 166743; -- was: Raw Material
UPDATE `creature_template` SET `name` = 'Breka Grimaxe' WHERE `entry` = 166784; -- was: Grunt Throg
UPDATE `creature_template` SET `name` = 'Warlord Breka Grimaxe' WHERE `entry` = 166906; -- was: Thrall
UPDATE `creature_template` SET `name` = 'Horde Sparring Partner' WHERE `entry` = 166916; -- was: Warlord Breka Grimaxe
UPDATE `creature_template` SET `name` = 'Shuja Grimaxe' WHERE `entry` = 167290; -- was: Wrathion
UPDATE `creature_template` SET `name` = 'Eye of Courage' WHERE `entry` = 167511; -- was: Paragon of Courage
UPDATE `creature_template` SET `name` = 'Eye of Wisdom' WHERE `entry` = 167513; -- was: Paragon of Wisdom
UPDATE `creature_template` SET `name` = 'Eye of Humility' WHERE `entry` = 167515; -- was: Paragon of Humility
UPDATE `creature_template` SET `name` = 'Eye of Purity' WHERE `entry` = 167516; -- was: Paragon of Purity
UPDATE `creature_template` SET `name` = 'Shuja Grimaxe' WHERE `entry` = 167630; -- was: Crenna Earth-Daughter
UPDATE `creature_template` SET `name` = 'Wrathion' WHERE `entry` = 167631; -- was: Herbert Gloomburst
UPDATE `creature_template` SET `name` = 'Breka Grimaxe' WHERE `entry` = 167632; -- was: Wrathion
UPDATE `creature_template` SET `name` = 'Warlord Breka Grimaxe' WHERE `entry` = 167663; -- was: Kalecgos
UPDATE `creature_template` SET `name` = 'Breka Grimaxe' WHERE `entry` = 167913; -- was: Grunt Throg
UPDATE `creature_template` SET `name` = 'Kill Credit: Lysonia Confronted' WHERE `entry` = 170308; -- was: Lysonia
UPDATE `creature_template` SET `name` = 'Kill Credit: Crest Activated' WHERE `entry` = 174184; -- was: Crest Activeted
UPDATE `creature_template` SET `name` = 'Eye of Loyalty' WHERE `entry` = 174542; -- was: Paragon of Loyalty
UPDATE `creature_template` SET `name` = 'MS Lifter' WHERE `entry` = 176078; -- was: Mawsworn Warden
UPDATE `creature_template` SET `name` = 'Necropolis: Zerekriss' WHERE `entry` = 176400; -- was: |cFFFFFFFF|rNecropolis: Zerekriss
UPDATE `creature_template` SET `name` = 'Thrall' WHERE `entry` = 176595; -- was: Boxy Joxy
UPDATE `creature_template` SET `name` = 'Jaina Proudmoore' WHERE `entry` = 176596; -- was: Rocko Dynamite
UPDATE `creature_template` SET `name` = 'Forsworn Prisoner' WHERE `entry` = 177309; -- was: Forsworn Prisonor
UPDATE `creature_template` SET `name` = 'Credit - Device 1 Placed' WHERE `entry` = 178307; -- was: Aural Sequencer Prime placed
UPDATE `creature_template` SET `name` = 'Credit - Device 2 Placed' WHERE `entry` = 178308; -- was: Aural Sequencer Relay placed
UPDATE `creature_template` SET `name` = 'Credit - Device 3 Placed' WHERE `entry` = 178309; -- was: Aural Sequencer Ground placed
UPDATE `creature_template` SET `name` = 'Asotera' WHERE `entry` = 178425; -- was: Wildseeds
UPDATE `creature_template` SET `name` = 'Credit - Wrath of Odyn Created' WHERE `entry` = 178489; -- was: Wrath of Odyn formed
UPDATE `creature_template` SET `name` = 'Credit - Ethereal Cloak Used' WHERE `entry` = 178953; -- was: Ethereal Cloak Used
UPDATE `creature_template` SET `name` = '(Bunny) Sessile + Large AOI' WHERE `entry` = 180538; -- was: (Bunny)Sessile+Large AOI
UPDATE `creature_template` SET `name` = 'Jeff Test Creature' WHERE `entry` = 180827; -- was: Owen Test Creature
UPDATE `creature_template` SET `name` = 'Generic - Empty Bunny' WHERE `entry` = 181029; -- was: Generic-Empty Bunny
UPDATE `creature_template` SET `name` = 'Spell Target (DNT)' WHERE `entry` = 181132; -- was: Spell Target
UPDATE `creature_template` SET `name` = 'Young Crasher' WHERE `entry` = 181518; -- was: Tyranny
UPDATE `creature_template` SET `name` = 'Olphis the Molten' WHERE `entry` = 181875; -- was: Olphisthe Molten
UPDATE `creature_template` SET `name` = 'Kill Credit: Spectral Bound Chest' WHERE `entry` = 182177; -- was: Kill Credit
UPDATE `creature_template` SET `name` = 'Encrypted Banner of the Opportune' WHERE `entry` = 182459; -- was: PH - Banner of the Opportune
UPDATE `creature_template` SET `name` = 'Shrouded Banner of the Opportune' WHERE `entry` = 182461; -- was: PH - Banner of the Opportune
UPDATE `creature_template` SET `name` = 'Summoned Lava Elemental' WHERE `entry` = 182815; -- was: SummonedLava Elemental
UPDATE `creature_template` SET `name` = 'Summoned Lava Elemental' WHERE `entry` = 182816; -- was: SummonedLava Elemental
UPDATE `creature_template` SET `name` = 'Helping Hand' WHERE `entry` = 183335; -- was: Rupert'sHelping Hand
UPDATE `creature_template` SET `name` = 'Warlord Breka Grimaxe' WHERE `entry` = 184452; -- was: WarlordBreka Grimaxe
UPDATE `creature_template` SET `name` = 'The Defiant Dragonscale' WHERE `entry` = 184807; -- was: TheDefiant Dragonscale
UPDATE `creature_template` SET `name` = 'Primal Scythid Queen' WHERE `entry` = 184853; -- was: PrimalScythid Queen
UPDATE `creature_template` SET `name` = 'Husk of the Jailer' WHERE `entry` = 185432; -- was: Thornmaw Test
UPDATE `creature_template` SET `name` = 'Entranced Water Elemental' WHERE `entry` = 185490; -- was: EntrancedWater Elemental
UPDATE `creature_template` SET `name` = 'Healing Wing Messenger' WHERE `entry` = 185754; -- was: Talon Mender
UPDATE `creature_template` SET `name` = 'Doventhal the Chosen' WHERE `entry` = 186163; -- was: Doventhalthe Chosen
UPDATE `creature_template` SET `name` = 'Generic - Empty Bunny' WHERE `entry` = 186241; -- was: Generic-Empty Bunny
UPDATE `creature_template` SET `name` = 'Fao the Relentless' WHERE `entry` = 186331; -- was: Faothe Relentless
UPDATE `creature_template` SET `name` = 'Horace "Scalding" Stern' WHERE `entry` = 186430; -- was: Horace ScaldingStern
UPDATE `creature_template` SET `name` = 'Pirdan the Blinder' WHERE `entry` = 186512; -- was: PirdanThe Blinder
UPDATE `creature_template` SET `name` = 'Dragonbane Cauldron Keeper' WHERE `entry` = 186606; -- was: DragonbaneCauldron Keeper
UPDATE `creature_template` SET `name` = 'Dragonbane Earth Warden' WHERE `entry` = 186608; -- was: DragonbaneEarth Warden
UPDATE `creature_template` SET `name` = 'Blacktalon Pack Goat' WHERE `entry` = 186763; -- was: BlacktalonPack Goat
UPDATE `creature_template` SET `name` = 'Blacktalon Pack Beast' WHERE `entry` = 186764; -- was: BlacktalonPack Beast
UPDATE `creature_template` SET `name` = 'Life Pools Crasher' WHERE `entry` = 187105; -- was: LifePools Crasher
UPDATE `creature_template` SET `name` = 'Life Pools Screecher' WHERE `entry` = 187106; -- was: LifePools Screecher
UPDATE `creature_template` SET `name` = 'Life Pools Stalwart' WHERE `entry` = 187107; -- was: LifePools Stalwart
UPDATE `creature_template` SET `name` = 'Ancient of Shelter' WHERE `entry` = 187110; -- was: Ancientof Shelter
UPDATE `creature_template` SET `name` = 'Klozicc the Ascended' WHERE `entry` = 187209; -- was: Kloziccthe Ascended
UPDATE `creature_template` SET `name` = 'Igys the Believer' WHERE `entry` = 187275; -- was: Igysthe Believer
UPDATE `creature_template` SET `name` = 'Borrowed Otter Mount' WHERE `entry` = 187295; -- was: BorrowedOtter Mount
UPDATE `creature_template` SET `name` = 'Primal Lava Elemental' WHERE `entry` = 187321; -- was: PrimalLava Elemental
UPDATE `creature_template` SET `name` = 'Primal Earth Elemental' WHERE `entry` = 187322; -- was: PrimalEarth Elemental
UPDATE `creature_template` SET `name` = '(Bunny) Sessile (FX)' WHERE `entry` = 187348; -- was: (Bunny)Sessile (FX)
UPDATE `creature_template` SET `name` = 'Distressed Riverbeast Calf' WHERE `entry` = 187462; -- was: DistressedRiverbeast Calf
UPDATE `creature_template` SET `name` = 'Trapped Sea Turtle' WHERE `entry` = 187469; -- was: TrappedSea Turtle
UPDATE `creature_template` SET `name` = 'Ball of Magma' WHERE `entry` = 187586; -- was: Ballof Magma
UPDATE `creature_template` SET `name` = 'Disgruntled Riverbeast Matriarch' WHERE `entry` = 187620; -- was: DisgruntledRiverbeast Matriarch
UPDATE `creature_template` SET `name` = 'Ball of Magma' WHERE `entry` = 187670; -- was: Ballof Magma
UPDATE `creature_template` SET `name` = 'Anhydros the Tidetaker' WHERE `entry` = 187945; -- was: Anhydrosthe Tidetaker
UPDATE `creature_template` SET `name` = 'Obsidian Outcasts Wagon' WHERE `entry` = 188010; -- was: ObsidianOutcasts Wagon
UPDATE `creature_template` SET `name` = 'Tuskarr Training Dummy' WHERE `entry` = 188352; -- was: TuskarrTraining Dummy
UPDATE `creature_template` SET `name` = 'Examiner Tae\'shara Bloodwatcher' WHERE `entry` = 188503; -- was: ExaminerTae'shara Bloodwatcher
UPDATE `creature_template` SET `name` = 'Fire Elemental' WHERE `entry` = 188514; -- was: Primal Fire Elemental
UPDATE `creature_template` SET `name` = 'Zhurtan the Riverboiler' WHERE `entry` = 188687; -- was: Zhurtanthe Riverboiler
UPDATE `creature_template` SET `name` = 'Potion Cauldron of Ultimate Power (Quality: 1)' WHERE `entry` = 188756; -- was: Potion Cauldron of Ultimate Power |A:Professions-Icon-Quality-Tier1-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Potion Cauldron of Ultimate Power (Quality: 2)' WHERE `entry` = 188839; -- was: Potion Cauldron of Ultimate Power |A:Professions-Icon-Quality-Tier2-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Potion Cauldron of Ultimate Power (Quality: 3)' WHERE `entry` = 188841; -- was: Potion Cauldron of Ultimate Power |A:Professions-Icon-Quality-Tier3-Small:20:20|a
UPDATE `creature_template` SET `name` = 'John Stelle III' WHERE `entry` = 188904; -- was: JohnStelle III
UPDATE `creature_template` SET `name` = 'Tragically Deceased Riverbeast' WHERE `entry` = 189613; -- was: TragicallyDeceased Riverbeast
UPDATE `creature_template` SET `name` = 'Tragically Deceased Waterfowl' WHERE `entry` = 189659; -- was: TragicallyDeceased Waterfowl
UPDATE `creature_template` SET `name` = 'Snoozing Basilisk Bull' WHERE `entry` = 189757; -- was: SnoozingBasilisk Bull
UPDATE `creature_template` SET `name` = 'Unsettled Rubble' WHERE `entry` = 189795; -- was: UnSET tled Rubble
UPDATE `creature_template` SET `name` = 'Hanging Spider Vehicle' WHERE `entry` = 189826; -- was: HangingSpider Vehicle
UPDATE `creature_template` SET `name` = 'Elemental Target [DNT]' WHERE `entry` = 189881; -- was: ElementalTarget [DNT]
UPDATE `creature_template` SET `name` = 'Primalist Target [DNT]' WHERE `entry` = 190064; -- was: PrimalistTarget [DNT]
UPDATE `creature_template` SET `name` = 'Infused Dragon Egg' WHERE `entry` = 190090; -- was: InfusedDragon Egg
UPDATE `creature_template` SET `name` = 'Fretful Riverbeast Elder' WHERE `entry` = 190144; -- was: FretfulRiverbeast Elder
UPDATE `creature_template` SET `name` = 'Egg Returned to Safety Kill Credit [DNT]' WHERE `entry` = 190211; -- was: EggReturnedtoSafetyKillCredit [DNT]
UPDATE `creature_template` SET `name` = 'Fretful Riverbeast Calf' WHERE `entry` = 190301; -- was: FretfulRiverbeast Calf
UPDATE `creature_template` SET `name` = 'Tuskarr Training Dummy' WHERE `entry` = 190621; -- was: TuskarrTraining Dummy
UPDATE `creature_template` SET `name` = 'Tuskarr Training Dummy' WHERE `entry` = 190623; -- was: TuskarrTraining Dummy
UPDATE `creature_template` SET `name` = 'Tuskarr Training Dummy' WHERE `entry` = 190624; -- was: TuskarrTraining Dummy
UPDATE `creature_template` SET `name` = 'Monsoo, The Boiling Rage' WHERE `entry` = 190718; -- was: Monsoo,TheBoiling Rage
UPDATE `creature_template` SET `name` = 'Injured Ruby Culler' WHERE `entry` = 190771; -- was: InjuredRuby Culler
UPDATE `creature_template` SET `name` = 'Soil Bunny [DNT]' WHERE `entry` = 190852; -- was: SoilBunny [DNT]
UPDATE `creature_template` SET `name` = 'Aizir the Inflamed' WHERE `entry` = 191304; -- was: Aizirthe Inflamed
UPDATE `creature_template` SET `name` = 'Herald of Frost' WHERE `entry` = 191315; -- was: Heraldof Frost
UPDATE `creature_template` SET `name` = 'Searing Flame Harchek' WHERE `entry` = 191476; -- was: SearingFlame Harchek
UPDATE `creature_template` SET `name` = 'Gragza the Dragon-Breaker' WHERE `entry` = 191507; -- was: Gragzathe Dragon-Breaker
UPDATE `creature_template` SET `name` = 'Young Wind Serpent' WHERE `entry` = 191647; -- was: YoungWind Serpent
UPDATE `creature_template` SET `name` = 'Thunder Lizard Alpha' WHERE `entry` = 191825; -- was: ThunderLizard Alpha
UPDATE `creature_template` SET `name` = 'Mature Thunder Lizard' WHERE `entry` = 191826; -- was: MatureThunder Lizard
UPDATE `creature_template` SET `name` = 'Thunder Lizard Calf' WHERE `entry` = 191828; -- was: ThunderLizard Calf
UPDATE `creature_template` SET `name` = 'Primalist Lava Conduit' WHERE `entry` = 191886; -- was: PrimalistLava Conduit
UPDATE `creature_template` SET `name` = 'Ruby Dragon Eggs' WHERE `entry` = 191904; -- was: RubyDragon Eggs
UPDATE `creature_template` SET `name` = 'Hornstrider Corpse Pile' WHERE `entry` = 191938; -- was: HornstriderCorpse Pile
UPDATE `creature_template` SET `name` = 'Baby Sea Turtle' WHERE `entry` = 192143; -- was: BabySea Turtle
UPDATE `creature_template` SET `name` = 'Elder Sea Turtle' WHERE `entry` = 192154; -- was: ElderSea Turtle
UPDATE `creature_template` SET `name` = 'Zayn Starmaker' WHERE `entry` = 192565; -- was: Krillonn
UPDATE `creature_template` SET `name` = '[DND] Air Storm' WHERE `entry` = 192580; -- was: [DND]Air Storm
UPDATE `creature_template` SET `name` = 'Charred Argali Corpse' WHERE `entry` = 192624; -- was: CharredArgali Corpse
UPDATE `creature_template` SET `name` = 'Beast Handler Tunse' WHERE `entry` = 193021; -- was: BeastHandler Tunse
UPDATE `creature_template` SET `name` = 'Head Chef Stacks' WHERE `entry` = 193121; -- was: HeadChef Stacks
UPDATE `creature_template` SET `name` = 'Terillod the Devout' WHERE `entry` = 193171; -- was: Terillodthe Devout
UPDATE `creature_template` SET `name` = 'Storm Target [DNT]' WHERE `entry` = 193218; -- was: StormTarget [DNT]
UPDATE `creature_template` SET `name` = 'Dograc The Burning' WHERE `entry` = 193550; -- was: DogracThe Burning
UPDATE `creature_template` SET `name` = 'Infused Proto-Dragon Egg' WHERE `entry` = 193807; -- was: InfusedProto-Dragon Egg
UPDATE `creature_template` SET `name` = 'Vish the Sneak' WHERE `entry` = 193838; -- was: Vishthe Sneak
UPDATE `creature_template` SET `name` = 'Mature Obsidian Hornswog' WHERE `entry` = 193923; -- was: MatureObsidian Hornswog
UPDATE `creature_template` SET `name` = 'Elder Obsidian Hornswog' WHERE `entry` = 193926; -- was: ElderObsidian Hornswog
UPDATE `creature_template` SET `name` = 'Expedition Supply Kit' WHERE `entry` = 194440; -- was: ExpeditionSupply Kit
UPDATE `creature_template` SET `name` = 'Ka\'ro the Chopper' WHERE `entry` = 194471; -- was: Ka'rothe Chopper
UPDATE `creature_template` SET `name` = 'Apprentice Caretaker Zefren' WHERE `entry` = 194525; -- was: ApprenticeCaretaker Zefren
UPDATE `creature_template` SET `name` = 'Memory of a Watcher' WHERE `entry` = 194628; -- was: Memoryofa Watcher
UPDATE `creature_template` SET `name` = 'Memory of a Dragonspawn' WHERE `entry` = 194632; -- was: Memoryofa Dragonspawn
UPDATE `creature_template` SET `name` = 'Dragon Target [DNT]' WHERE `entry` = 194693; -- was: DragonTarget [DNT]
UPDATE `creature_template` SET `name` = 'Explorers\' League Scout' WHERE `entry` = 195508; -- was: Explorer's League Scout
UPDATE `creature_template` SET `name` = 'Explorers\' League Prospector' WHERE `entry` = 195511; -- was: Explorer's League Prospector
UPDATE `creature_template` SET `name` = 'Firava the Rekindler' WHERE `entry` = 195915; -- was: Firavathe Rekindler
UPDATE `creature_template` SET `name` = 'Expedition Scout Mirwen' WHERE `entry` = 195948; -- was: ExpeditionScout Mirwen
UPDATE `creature_template` SET `name` = 'Gushgut the Beaksinker' WHERE `entry` = 196056; -- was: Gushgutthe Beaksinker
UPDATE `creature_template` SET `name` = 'Khakad the Ancient' WHERE `entry` = 196379; -- was: Khakadthe Ancient
UPDATE `creature_template` SET `name` = 'Frizkon the Ancient' WHERE `entry` = 196380; -- was: Frizkonthe Ancient
UPDATE `creature_template` SET `name` = 'Mellg the Ancient' WHERE `entry` = 196381; -- was: Mellgthe Ancient
UPDATE `creature_template` SET `name` = 'Thornmu the Ancient' WHERE `entry` = 196382; -- was: Thornmuthe Ancient
UPDATE `creature_template` SET `name` = 'Quilmo the Ancient' WHERE `entry` = 196386; -- was: Quilmothe Ancient
UPDATE `creature_template` SET `name` = 'Invis Bunny Template - Gigantic AOI' WHERE `entry` = 196605; -- was: InvisBunnyTemplate-Gigantic AOI
UPDATE `creature_template` SET `name` = 'Time-Touched Falcon' WHERE `entry` = 196684; -- was: Time Trapped Falcon
UPDATE `creature_template` SET `name` = 'Time-Touched Hare' WHERE `entry` = 196690; -- was: Time Trapped Hare
UPDATE `creature_template` SET `name` = 'Sleepy Bakar' WHERE `entry` = 196697; -- was: Time Trapped Bakar
UPDATE `creature_template` SET `name` = 'Ruby Life Pools' WHERE `entry` = 196811; -- was: RubyLife Pools
UPDATE `creature_template` SET `name` = 'Gurblbrblr the Invader' WHERE `entry` = 197211; -- was: Gurblbrblrthe Invader
UPDATE `creature_template` SET `name` = 'Tamed Magmammoth Calf' WHERE `entry` = 197224; -- was: TamedMagmammoth Calf
UPDATE `creature_template` SET `name` = 'Barrel of Assorted Seafood' WHERE `entry` = 197412; -- was: BarrelofAssorted Seafood
UPDATE `creature_template` SET `name` = 'Time-Touched Thresher' WHERE `entry` = 197422; -- was: Time Trapped Thresher
UPDATE `creature_template` SET `name` = 'Time-Touched Skitterfly' WHERE `entry` = 197434; -- was: Time Trapped Skitterfly
UPDATE `creature_template` SET `name` = 'Campfire Bunny [DNT]' WHERE `entry` = 197441; -- was: CampfireBunny [DNT]
UPDATE `creature_template` SET `name` = 'The Rugged Dragonscale' WHERE `entry` = 197503; -- was: TheRugged Dragonscale
UPDATE `creature_template` SET `name` = 'Temporally-Touched Butterfly' WHERE `entry` = 197552; -- was: Time Trapped Butterfly
UPDATE `creature_template` SET `name` = 'Memory of a Crate' WHERE `entry` = 197606; -- was: Memoryofa Crate
UPDATE `creature_template` SET `name` = 'Memory of a Book' WHERE `entry` = 197608; -- was: Memoryofa Book
UPDATE `creature_template` SET `name` = '(Bunny) Sessile + Gigantic AOI' WHERE `entry` = 197611; -- was: (Bunny)Sessile+Gigantic AOI
UPDATE `creature_template` SET `name` = '"Resting" Shrineguard' WHERE `entry` = 197702; -- was: RestingShrineguard
UPDATE `creature_template` SET `name` = '(Bunny) See Ramp Alliance Dock - DO NOT REUSE' WHERE `entry` = 197899; -- was: (Bunny)SeeRampAllianceDock-DONOT REUSE
UPDATE `creature_template` SET `name` = 'Primal Turtle Ritual Site' WHERE `entry` = 198042; -- was: PrimalTurtleRitual Site
UPDATE `creature_template` SET `name` = 'Rupert, the Gentleman Elemental' WHERE `entry` = 198160; -- was: Rupert,theGentleman Elemental
UPDATE `creature_template` SET `name` = 'Trothar the Tracker' WHERE `entry` = 198182; -- was: Trotharthe Tracker
UPDATE `creature_template` SET `name` = 'Lightning Shield Bunny [DNT]' WHERE `entry` = 198194; -- was: LightningShieldBunny [DNT]
UPDATE `creature_template` SET `name` = 'Goblin Trap [DNT]' WHERE `entry` = 198195; -- was: GoblinTrap [DNT]
UPDATE `creature_template` SET `name` = '(Bunny) Crow\'s Nest' WHERE `entry` = 198362; -- was: (Bunny)Crow's Nest
UPDATE `creature_template` SET `name` = '(Bunny) Crow\'s Nest [DNT]' WHERE `entry` = 198363; -- was: (Bunny)Crow'sNest [DNT]
UPDATE `creature_template` SET `name` = '(Bunny) Crow\'s Nest [DNT]' WHERE `entry` = 198367; -- was: (Bunny)Crow'sNest [DNT]
UPDATE `creature_template` SET `name` = 'Assistant Dilya' WHERE `entry` = 198589; -- was: Dilya
UPDATE `creature_template` SET `name` = 'Trained Lizard' WHERE `entry` = 198815; -- was: Fledgling Thunder Lizard
UPDATE `creature_template` SET `name` = 'Ebyssian' WHERE `entry` = 199144; -- was: Spiritwalker Ebonhorn
UPDATE `creature_template` SET `name` = 'Assistant Zaa\'je' WHERE `entry` = 199164; -- was: Zaa'je
UPDATE `creature_template` SET `name` = 'Mr. Geramaz' WHERE `entry` = 199415; -- was: Sr. Grumbles
UPDATE `creature_template` SET `name` = 'Pan the Kind Hand' WHERE `entry` = 199701; -- was: PantheKind Hand
UPDATE `creature_template` SET `name` = 'Scalecommander Emberthal' WHERE `entry` = 201401; -- was: Hadexian
UPDATE `creature_template` SET `name` = 'Draconic Phial Cauldron (Quality: 1)' WHERE `entry` = 202688; -- was: Draconic Phial Cauldron |A:Professions-Icon-Quality-Tier1-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Draconic Phial Cauldron (Quality: 2)' WHERE `entry` = 202709; -- was: Draconic Phial Cauldron |A:Professions-Icon-Quality-Tier2-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Draconic Phial Cauldron (Quality: 3)' WHERE `entry` = 202711; -- was: Draconic Phial Cauldron |A:Professions-Icon-Quality-Tier3-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Algari Flask Cauldron (Quality: 1)' WHERE `entry` = 216373; -- was: Algari Flask Cauldron |A:Professions-Icon-Quality-Tier1-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Algari Flask Cauldron (Quality: 2)' WHERE `entry` = 216374; -- was: Algari Flask Cauldron |A:Professions-Icon-Quality-Tier2-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Algari Flask Cauldron (Quality: 3)' WHERE `entry` = 216375; -- was: Algari Flask Cauldron |A:Professions-Icon-Quality-Tier3-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Algari Potion Cauldron (Quality: 1)' WHERE `entry` = 216569; -- was: Algari Potion Cauldron |A:Professions-Icon-Quality-Tier1-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Algari Potion Cauldron (Quality: 2)' WHERE `entry` = 216570; -- was: Algari Potion Cauldron |A:Professions-Icon-Quality-Tier2-Small:20:20|a
UPDATE `creature_template` SET `name` = 'Algari Potion Cauldron (Quality: 3)' WHERE `entry` = 216571; -- was: Algari Potion Cauldron |A:Professions-Icon-Quality-Tier3-Small:20:20|a
UPDATE `creature_template` SET `name` = 'The Puppetmaster?' WHERE `entry` = 220507; -- was: The Puppetmaster
UPDATE `creature_template` SET `name` = 'Thrauna' WHERE `entry` = 227801; -- was: Jeff the Flightmaster
UPDATE `creature_template` SET `name` = 'Brann Bronzebeard' WHERE `entry` = 228903; -- was: Renowned Explorer's Versatile Vest
UPDATE `creature_template` SET `name` = 'Voidbound Emissary' WHERE `entry` = 229537; -- was: Void Emissary
UPDATE `creature_template` SET `name` = 'Ptolemi Steadysketch' WHERE `entry` = 230650; -- was: Ptoleml Steadysketch
UPDATE `creature_template` SET `name` = 'Void-Cursed Crusher' WHERE `entry` = 231156; -- was: Void-Cursed Crusher","Void Cursed Crusher
UPDATE `creature_template` SET `name` = 'Crystal' WHERE `entry` = 233425; -- was: Invisible Bunny - Crystal Aligned [DNT]
UPDATE `creature_template` SET `name` = 'Lightfueled Defender' WHERE `entry` = 236312; -- was: Rutaani Fighter
UPDATE `creature_template` SET `name` = 'Lightbound Thorncaller' WHERE `entry` = 236313; -- was: Rutaani Fighter
UPDATE `creature_template` SET `name` = 'Lightdriven Leafmancer' WHERE `entry` = 236314; -- was: Rutaani Leafmancer
UPDATE `creature_template` SET `name` = 'Lightfused Leafmaster' WHERE `entry` = 236315; -- was: Rutaani Leafmaster
UPDATE `creature_template` SET `name` = 'Lightblinded Rutaani Grovewarden' WHERE `entry` = 237394; -- was: Rutaani Fighter
UPDATE `creature_template` SET `name` = 'Erratic Light Wyrm' WHERE `entry` = 237399; -- was: Invasive Light Wyrm
UPDATE `creature_template` SET `name` = 'Culled Lynx' WHERE `entry` = 238077; -- was: Frost-Trapped Lynx
UPDATE `creature_template` SET `name` = 'Injured Defender' WHERE `entry` = 239455; -- was: Injured Defenders
UPDATE `creature_template` SET `name` = 'Sanctum of Light' WHERE `entry` = 239527; -- was: Kill Credit: Arrive at Silvermoon
UPDATE `creature_template` SET `name` = 'Inquisitive Haranir' WHERE `entry` = 240539; -- was: Inqusitive Haranir
UPDATE `creature_template` SET `name` = 'Injured Citizen' WHERE `entry` = 240543; -- was: Injured Citizens
UPDATE `creature_template` SET `name` = 'Oblivion Ooze' WHERE `entry` = 240552; -- was: Hungering Void
UPDATE `creature_template` SET `name` = 'Irradiant Thornmaw' WHERE `entry` = 240644; -- was: Lightbloom Ent
UPDATE `creature_template` SET `name` = 'Assisting Paladin' WHERE `entry` = 240662; -- was: Arator
UPDATE `creature_template` SET `name` = 'Inquisitive Haranir' WHERE `entry` = 240663; -- was: Inqusitive Haranir
UPDATE `creature_template` SET `name` = 'Lightfused Leafmancer' WHERE `entry` = 240981; -- was: Rutanni Leafmancer
UPDATE `creature_template` SET `name` = 'Lightfueled Defender' WHERE `entry` = 240983; -- was: Rutanni Fighter
UPDATE `creature_template` SET `name` = 'Lightfueled Defender' WHERE `entry` = 240991; -- was: Rutanni Fighter
UPDATE `creature_template` SET `name` = 'Seething Slayer' WHERE `entry` = 241254; -- was: Incensed Interficio
UPDATE `creature_template` SET `name` = 'Lightdriven Leafslasher' WHERE `entry` = 241545; -- was: Rutaani Rogue
UPDATE `creature_template` SET `name` = 'Cosmic Ascendant' WHERE `entry` = 241685; -- was: Voidbound Maleficus
UPDATE `creature_template` SET `name` = 'Public Carriage' WHERE `entry` = 242053; -- was: Public Carriage","Wagon
UPDATE `creature_template` SET `name` = 'Stronghold Enforcer' WHERE `entry` = 242917; -- was: Stronghold Custos
UPDATE `creature_template` SET `name` = 'Darkspawn' WHERE `entry` = 244171; -- was: Voidspawn
UPDATE `creature_template` SET `name` = 'Wrathbound Voidwraith' WHERE `entry` = 245931; -- was: Voidwhisperer
UPDATE `creature_template` SET `name` = 'Cauldron of Sin\'dorei Flasks' WHERE `entry` = 246004; -- was: Cauldron of Sin'dorei Flasks |A:Professions-ChatIcon-Quality-12-Tier1:20:20|a
UPDATE `creature_template` SET `name` = 'Cauldron of Sin\'dorei Flasks' WHERE `entry` = 246105; -- was: Cauldron of Sin'dorei Flasks |A:Professions-ChatIcon-Quality-12-Tier2:20:20|a
UPDATE `creature_template` SET `name` = 'Voidlight Potion Cauldron' WHERE `entry` = 246112; -- was: Voidlight Potion Cauldron |A:Professions-ChatIcon-Quality-12-Tier1:20:20|a
UPDATE `creature_template` SET `name` = 'Voidlight Potion Cauldron' WHERE `entry` = 246117; -- was: Voidlight Potion Cauldron |A:Professions-ChatIcon-Quality-12-Tier2:20:20|a
UPDATE `creature_template` SET `name` = 'Cult Adept' WHERE `entry` = 246350; -- was: Twilight Adept
UPDATE `creature_template` SET `name` = 'Bladesworn Cultist' WHERE `entry` = 246352; -- was: Twilight Bladesworn
UPDATE `creature_template` SET `name` = 'Ogre Browbeater' WHERE `entry` = 246359; -- was: Twilight Browbeater
UPDATE `creature_template` SET `name` = 'Umbral Skullcrusher' WHERE `entry` = 246361; -- was: Twilight Skullcrusher
UPDATE `creature_template` SET `name` = 'The Talon of Jan\'alai' WHERE `entry` = 246501; -- was: The Talon of Janali
UPDATE `creature_template` SET `name` = 'Leafweaver' WHERE `entry` = 246629; -- was: Lightbloom Leafweaver
UPDATE `creature_template` SET `name` = 'Thornblade' WHERE `entry` = 246630; -- was: Lightbloom Thornblade
UPDATE `creature_template` SET `name` = 'Lightcrazed Undergrowth' WHERE `entry` = 246634; -- was: Lightbloom Undergrowth
UPDATE `creature_template` SET `name` = 'Radiant Chloromancer' WHERE `entry` = 246635; -- was: Lightbloom Chloromancer
UPDATE `creature_template` SET `name` = 'Sapshield Defender' WHERE `entry` = 246636; -- was: Lightbloom Sapshield
UPDATE `creature_template` SET `name` = 'Thornmaw Briarblaze' WHERE `entry` = 246637; -- was: Lightbloom Thornmaw
UPDATE `creature_template` SET `name` = 'Stumpspreader' WHERE `entry` = 246638; -- was: Lightbloom Stumpspreader
UPDATE `creature_template` SET `name` = 'Grovecrawler Lightleaf' WHERE `entry` = 246674; -- was: Lightbloom Grovecrawler
UPDATE `creature_template` SET `name` = 'Apprentice Corpsecaller' WHERE `entry` = 246815; -- was: Vilebranch Corpsecaller
UPDATE `creature_template` SET `name` = 'Lurking Shadowstalker' WHERE `entry` = 246825; -- was: Vilebranch Shadowstalker
UPDATE `creature_template` SET `name` = 'Necrohex Soulbinder' WHERE `entry` = 246831; -- was: Vilebranch Drum-Master
UPDATE `creature_template` SET `name` = 'Leering Skulltaker' WHERE `entry` = 246834; -- was: Vilebranch Skulltaker
UPDATE `creature_template` SET `name` = 'The Talon of Jan\'alai' WHERE `entry` = 246944; -- was: The Talon of Janali
UPDATE `creature_template` SET `name` = 'The Talon of Jan\'alai' WHERE `entry` = 246945; -- was: The Talon of Janali
UPDATE `creature_template` SET `name` = 'The Talon of Jan\'alai' WHERE `entry` = 247172; -- was: The Talon of Janali
UPDATE `creature_template` SET `name` = 'The Talon of Jan\'alai' WHERE `entry` = 247344; -- was: The Talon of Janali
UPDATE `creature_template` SET `name` = 'Mother Goldskimmer' WHERE `entry` = 247928; -- was: Sister Goldskimmer
UPDATE `creature_template` SET `name` = 'Unstable Oozeling' WHERE `entry` = 248145; -- was: Unstable Oozing
UPDATE `creature_template` SET `name` = 'Mot\'amra' WHERE `entry` = 248597; -- was: Bound Loa
UPDATE `creature_template` SET `name` = 'Unstable Oozeling' WHERE `entry` = 248716; -- was: Unstable Oozing
UPDATE `creature_template` SET `name` = 'Void Terror' WHERE `entry` = 249086; -- was: Void Infuser
UPDATE `creature_template` SET `name` = 'Dusty Lurker Web' WHERE `entry` = 249273; -- was: Dusty Web
UPDATE `creature_template` SET `name` = 'Awe\'ohna' WHERE `entry` = 249403; -- was: Petalwing
UPDATE `creature_template` SET `name` = 'Dreadflail' WHERE `entry` = 251024; -- was: Null Guardian
UPDATE `creature_template` SET `name` = 'Grand Nullifier' WHERE `entry` = 251031; -- was: Wretched Supplicant
UPDATE `creature_template` SET `name` = 'Lightbloated Magister' WHERE `entry` = 251769; -- was: Infested Magister
UPDATE `creature_template` SET `name` = 'Lady Jaxiera' WHERE `entry` = 252007; -- was: Jaxina
UPDATE `creature_template` SET `name` = 'Ley Line Stalker' WHERE `entry` = 252146; -- was: Leyline Stalker
UPDATE `creature_template` SET `name` = 'Ley Line Focuser' WHERE `entry` = 252600; -- was: Leyline Focuser
UPDATE `creature_template` SET `name` = 'Ley Line Port Stalker' WHERE `entry` = 252601; -- was: Leyline Port Stalker
UPDATE `creature_template` SET `name` = 'Stolen Ley Line Focuser' WHERE `entry` = 252611; -- was: Stolen Leyline Focuser
UPDATE `creature_template` SET `name` = 'Zaib\'yan' WHERE `entry` = 253458; -- was: Zil'jan
UPDATE `creature_template` SET `name` = 'The Talon of Jan\'alai' WHERE `entry` = 253903; -- was: The Talon of Janali
UPDATE `creature_template` SET `name` = 'L\'ura' WHERE `entry` = 253979; -- was: The Black Aperture
UPDATE `creature_template` SET `name` = 'Scaly Scratcher' WHERE `entry` = 253993; -- was: Scaley Scratcher
UPDATE `creature_template` SET `name` = 'Kel\'vujo' WHERE `entry` = 253997; -- was: Kel'venko
UPDATE `creature_template` SET `name` = 'Kel\'vujo' WHERE `entry` = 253999; -- was: Kel'venko
UPDATE `creature_template` SET `name` = 'Kel\'vujo' WHERE `entry` = 254261; -- was: Kel'venko
UPDATE `creature_template` SET `name` = 'Kel\'vujo' WHERE `entry` = 254298; -- was: Kel'venko
UPDATE `creature_template` SET `name` = 'Mother Goldskimmer' WHERE `entry` = 254300; -- was: Sister Goldskimmer
UPDATE `creature_template` SET `name` = 'Giant Cursed Bullfrog' WHERE `entry` = 254533; -- was: Giant Cursed Bulfrog
UPDATE `creature_template` SET `name` = 'Voice from the Orb' WHERE `entry` = 254701; -- was: Bunny (DNT)
UPDATE `creature_template` SET `name` = 'Void Pylon' WHERE `entry` = 256539; -- was: Generic - Empty Bunny
UPDATE `creature_template` SET `name` = 'Void Pylon' WHERE `entry` = 256554; -- was: Generic - Empty Bunny
UPDATE `creature_template` SET `name` = 'Void Pylon' WHERE `entry` = 256556; -- was: Generic - Empty Bunny
UPDATE `creature_template` SET `name` = 'Stronghold Slayer' WHERE `entry` = 256596; -- was: Stronghold Interficio
UPDATE `creature_template` SET `name` = 'Stronghold Ascendant' WHERE `entry` = 256597; -- was: Stronghold Maleficus
UPDATE `creature_template` SET `name` = 'Stronghold Enforcer' WHERE `entry` = 256603; -- was: Stronghold Custos
UPDATE `creature_template` SET `name` = 'Ley Line Focuser' WHERE `entry` = 256717; -- was: Leyline Focuser
UPDATE `creature_template` SET `name` = 'Ley Line Source' WHERE `entry` = 256718; -- was: Leyline Source
UPDATE `creature_template` SET `name` = 'Ley Line Conduit' WHERE `entry` = 256720; -- was: Leyline Conduit
UPDATE `creature_template` SET `name` = 'Ley Line Destination' WHERE `entry` = 256726; -- was: Leyline Destination
UPDATE `creature_template` SET `name` = 'Ley Line Focuser' WHERE `entry` = 256748; -- was: Leyline Focuser
UPDATE `creature_template` SET `name` = 'Voidbound Annihilator' WHERE `entry` = 256757; -- was: Abyssal Nightshade
UPDATE `creature_template` SET `name` = 'Ley Line Anomaly' WHERE `entry` = 256775; -- was: Leyline Anomaly
UPDATE `creature_template` SET `name` = 'Hurried Courier' WHERE `entry` = 256993; -- was: Lady Liadrin
UPDATE `creature_template` SET `name` = 'En\'liahn' WHERE `entry` = 256995; -- was: Amarakk
UPDATE `creature_template` SET `name` = 'Netherling' WHERE `entry` = 257266; -- was: Voidwyrm
UPDATE `creature_template` SET `name` = 'Unwieldy Gryphon' WHERE `entry` = 257876; -- was: Unweildy Gryphon
UPDATE `creature_template` SET `name` = 'Abyssal Malus' WHERE `entry` = 257950; -- was: Voidbound Malus
UPDATE `creature_template` SET `name` = 'Void-Corrupted Ley Line' WHERE `entry` = 258497; -- was: Void-Corrupted Leyline
UPDATE `creature_template` SET `name` = 'Ley Line Conduit' WHERE `entry` = 258706; -- was: Leyline Conduit
UPDATE `creature_template` SET `name` = 'Ley Line Conduit' WHERE `entry` = 258707; -- was: Leyline Conduit
UPDATE `creature_template` SET `name` = 'Ley Line Conduit' WHERE `entry` = 258708; -- was: Leyline Conduit
UPDATE `creature_template` SET `name` = 'Spellshield Collaborator' WHERE `entry` = 258709; -- was: Collaborationist Spellshield
UPDATE `creature_template` SET `name` = 'Shadowfused Sentinel' WHERE `entry` = 258712; -- was: Collaborationist Sentinel
UPDATE `creature_template` SET `name` = 'Ley Line' WHERE `entry` = 258829; -- was: Leyline
UPDATE `creature_template` SET `name` = 'Valeera\'s Agony' WHERE `entry` = 259126; -- was: Echo of Kathra'natir
UPDATE `creature_template` SET `name` = 'Stolen Ley Line Focuser' WHERE `entry` = 259356; -- was: Stolen Leyline Focuser
UPDATE `creature_template` SET `name` = 'Puddle-Jumper Shrine' WHERE `entry` = 259584; -- was: Puddle-Jumper's Shrine
UPDATE `creature_template` SET `name` = 'Myinia' WHERE `entry` = 259770; -- was: Dymyina
UPDATE `creature_template` SET `name` = 'Portal to Harandar' WHERE `entry` = 259832; -- was: Rootway to Harandar
UPDATE `creature_template` SET `name` = 'Brilliant Dispersion' WHERE `entry` = 260032; -- was: Core
UPDATE `creature_template` SET `name` = 'Raid Boss Tank Test Dummy' WHERE `entry` = 260139; -- was: Tank Test Dummy
